version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 251410
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb?schema=public
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  flyway:
    image: redgate/flyway
    container_name: flyway
    command: migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/mydb?schema=public
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 251410
    depends_on:
      - postgres
